export interface CUSTOMER_MODEL {
    id:number,
    name:string ,
    dateAndTime:string ,
    assigneeName:string ,
    phoneNumber:string ,
    status:CallStatus
}

export enum SORTBY {
  ascending_name = 'ascending_name' ,
  descending_name = 'descending_name' ,
  ascending_created = 'ascending_created' ,
  desceding_created = 'desceding_created' ,
}

export enum CallStatus {
    ABROAD_EDUCATION = 'Abroad Education',
    ADMISSION_DONE = 'Admission Done',
    CALL_AFTER_12TH_EXAM = 'Call after 12th Exam',
    CALL_BACK = 'Call Back',
    CALL_WAITING = 'Call Waiting',
    CALL_NOT_PICKED = 'Call Not Picked',
    CALL_AFTER_CAT_RESULT = 'Call after CAT Result',
    BUSY = 'Busy',
    CALL_AFTER_DEGREE_EXAM = 'Call after Degree Exam',
  }
  
 export const CUSTOMERS_LIST : CUSTOMER_MODEL[]= [
    {
      id: 1,
      name: 'John Doe',
      dateAndTime: '2024-01-01T09:45:00Z',
      assigneeName: 'Alice Smith',
      phoneNumber: '123-456-7890',
      status: CallStatus.ABROAD_EDUCATION,
    },
    {
      id: 2,
      name: 'Jane Johnson',
      dateAndTime: '2024-01-02T14:22:00Z',
      assigneeName: 'Bob Brown',
      phoneNumber: '987-654-3210',
      status: CallStatus.ADMISSION_DONE,
    },
    {
      id: 3,
      name: 'David Davis',
      dateAndTime: '2024-01-03T11:45:00Z',
      assigneeName: 'Emily White',
      phoneNumber: '555-123-4567',
      status: CallStatus.CALL_AFTER_12TH_EXAM,
    },
    {
      id: 4,
      name: 'Michael Miller',
      dateAndTime: '2024-01-04T17:30:00Z',
      assigneeName: 'Sophia Wilson',
      phoneNumber: '222-333-4444',
      status: CallStatus.CALL_BACK,
    },
    {
      id: 5,
      name: 'Daniel Moore',
      dateAndTime: '2024-01-05T10:12:00Z',
      assigneeName: 'Olivia Lee',
      phoneNumber: '666-555-4444',
      status: CallStatus.CALL_WAITING,
    },
    {
      id: 6,
      name: 'Ethan Evans',
      dateAndTime: '2024-01-06T13:45:00Z',
      assigneeName: 'Chloe Taylor',
      phoneNumber: '111-222-3333',
      status: CallStatus.CALL_NOT_PICKED,
    },
    {
      id: 7,
      name: 'Ava Martinez',
      dateAndTime: '2024-01-07T16:20:00Z',
      assigneeName: 'Noah Anderson',
      phoneNumber: '444-555-6666',
      status: CallStatus.CALL_AFTER_CAT_RESULT,
    },
    {
      id: 8,
      name: 'Sophie Harris',
      dateAndTime: '2024-01-08T08:30:00Z',
      assigneeName: 'Logan Jackson',
      phoneNumber: '777-888-9999',
      status: CallStatus.BUSY,
    },
    {
      id: 9,
      name: 'William Clark',
      dateAndTime: '2024-01-09T12:40:00Z',
      assigneeName: 'Grace Lewis',
      phoneNumber: '555-666-7777',
      status: CallStatus.CALL_AFTER_DEGREE_EXAM,
    },
    {
      id: 10,
      name: 'Mia Scott',
      dateAndTime: '2024-01-10T09:05:00Z',
      assigneeName: 'James Carter',
      phoneNumber: '999-888-7777',
      status: CallStatus.ABROAD_EDUCATION,
    },
    {
      id: 11,
      name: 'Liam Taylor',
      dateAndTime: '2024-01-11T14:18:00Z',
      assigneeName: 'Ella Martinez',
      phoneNumber: '111-999-8888',
      status: CallStatus.ADMISSION_DONE,
    },
    {
      id: 12,
      name: 'Aiden Moore',
      dateAndTime: '2024-01-12T11:32:00Z',
      assigneeName: 'Mia Davis',
      phoneNumber: '222-777-6666',
      status: CallStatus.CALL_AFTER_12TH_EXAM,
    },
    {
      id: 13,
      name: 'Zoe Jackson',
      dateAndTime: '2024-01-13T09:45:00Z',
      assigneeName: 'Noah White',
      phoneNumber: '888-777-6666',
      status: CallStatus.CALL_BACK,
    },
    {
      id: 14,
      name: 'Lucas Harris',
      dateAndTime: '2024-01-14T17:20:00Z',
      assigneeName: 'Chloe Clark',
      phoneNumber: '333-999-8888',
      status: CallStatus.CALL_WAITING,
    },
    {
      id: 15,
      name: 'Lily Brown',
      dateAndTime: '2024-01-15T13:10:00Z',
      assigneeName: 'Henry Smith',
      phoneNumber: '777-666-5555',
      status: CallStatus.CALL_NOT_PICKED,
    },
    {
      id: 16,
      name: 'Elijah Anderson',
      dateAndTime: '2024-01-16T15:48:00Z',
      assigneeName: 'Ava Martin',
      phoneNumber: '444-888-9999',
      status: CallStatus.CALL_AFTER_CAT_RESULT,
    },
    {
      id: 17,
      name: 'Scarlett Lewis',
      dateAndTime: '2024-01-17T12:25:00Z',
      assigneeName: 'Oliver Taylor',
      phoneNumber: '111-666-5555',
      status: CallStatus.BUSY,
    },
    {
      id: 18,
      name: 'Jackson Wilson',
      dateAndTime: '2024-01-18T08:55:00Z',
      assigneeName: 'Emily Clark',
      phoneNumber: '555-777-9999',
      status: CallStatus.CALL_AFTER_DEGREE_EXAM,
    },
    {
      id: 19,
      name: 'Penelope Moore',
      dateAndTime: '2024-01-19T08:55:00Z',
      assigneeName: 'Daniel Harris',
      phoneNumber: '222-444-6666',
      status: CallStatus.CALL_AFTER_CAT_RESULT,
    },
    {
      id: 20,
      name: 'Logan White',
      dateAndTime: '2024-01-20T11:10:00Z',
      assigneeName: 'Eva Martinez',
      phoneNumber: '111-555-9999',
      status: CallStatus.CALL_WAITING,
    },
  ];
  